version: 0.2
phases:
  install:
    commands:
      - npm install --prefix ./time-app/
      - export BUCKET=source.ops.acnonline.net
      - aws cloudformation package --template-file template.yaml --s3-bucket source.ops.acnonline.net --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - outputtemplate.yaml
